/*
 Navicat Premium Data Transfer

 Source Server         : db_of_openjianghu3
 Source Server Type    : MySQL
 Source Server Version : 50737
 Source Host           : 127.0.0.1:40003
 Source Schema         : fs_wms_purchase

 Target Server Type    : MySQL
 Target Server Version : 50737
 File Encoding         : 65001

 Date: 04/01/2023 21:26:18
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for _resource
-- ----------------------------
DROP TABLE IF EXISTS `_resource`;
CREATE TABLE `_resource` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `accessControlTable` varchar(255) DEFAULT NULL COMMENT '数据规则控制表',
  `resourceHook` text COMMENT '[ "before": {"service": "xx", "serviceFunction": "xxx"}, "after": [] }',
  `pageId` varchar(255) DEFAULT NULL COMMENT 'page id; E.g: index',
  `actionId` varchar(255) DEFAULT NULL COMMENT 'action id; E.g: selectXXXByXXX',
  `desc` varchar(255) DEFAULT NULL COMMENT '描述',
  `resourceType` varchar(255) DEFAULT NULL COMMENT 'resource 类型; E.g: auth service sql',
  `appDataSchema` text COMMENT 'appData 参数校验',
  `resourceData` text COMMENT 'resource 数据; { "service": "auth", "serviceFunction": "passwordLogin" } or  { "table": "${tableName}", "action": "select", "whereCondition": ".where(function() {this.whereNot( { recordStatus: \\"active\\" })})" }',
  `requestDemo` text COMMENT '请求Demo',
  `responseDemo` text COMMENT '响应Demo',
  `operation` varchar(255) DEFAULT 'insert' COMMENT '操作; insert, update, jhInsert, jhUpdate, jhDelete jhRestore',
  `operationByUserId` varchar(255) DEFAULT NULL COMMENT '操作者userId',
  `operationByUser` varchar(255) DEFAULT NULL COMMENT '操作者用户名',
  `operationAt` varchar(255) DEFAULT NULL COMMENT '操作时间; E.g: 2021-05-28T10:24:54+08:00 ',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=383 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='请求资源表; 软删除未启用; resourceId=`${appId}.${pageId}.${actionId}`';

-- ----------------------------
-- Records of _resource
-- ----------------------------
BEGIN;
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (1, NULL, NULL, 'login', 'passwordLogin', '✅登陆', 'service', '{}', '{ \"service\": \"user\", \"serviceFunction\": \"passwordLogin\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (2, NULL, NULL, 'allPage', 'logout', '✅登出', 'service', '{}', '{ \"service\": \"user\", \"serviceFunction\": \"logout\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (3, NULL, NULL, 'allPage', 'userInfo', '✅获取用户信息', 'service', '{}', '{ \"service\": \"user\", \"serviceFunction\": \"userInfo\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (4, NULL, NULL, 'allPage', 'getConstantList', '✅查询常量', 'sql', '{}', '{ \"table\": \"_constant\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (231, NULL, NULL, 'workflowManagement', 'selectItemList', '✅workflowManagement查询-查询列表', 'sql', '{}', '{\"table\": \"workflow\", \"operation\": \"select\"}', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (232, NULL, '{\"before\":[{\"service\":\"workflow\",\"serviceFunction\":\"createWorkflowId\"}]}', 'workflowManagement', 'insertItem', '✅workflowManagement查询-添加成员', 'sql', '{}', '{\"table\": \"workflow\", \"operation\": \"jhInsert\"}', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (233, NULL, NULL, 'workflowManagement', 'updateItem', '✅workflowManagement查询-更新成员', 'sql', '{}', '{\"table\": \"workflow\", \"operation\": \"jhUpdate\"}', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (234, NULL, NULL, 'workflowManagement', 'deleteItem', '✅workflowManagement查询-删除信息', 'sql', '{}', '{\"table\": \"workflow\", \"operation\": \"jhDelete\"}', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (235, NULL, '', 'workflowManagement', 'selectUserList', '✅查询-用户列表', 'sql', NULL, '{\"table\": \"_view01_user\", \"operation\": \"select\"}', '', '', 'update', 'vscode', 'vscode', '2022-07-04T22:27:58+08:00');
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (236, NULL, '', 'workflowManagement', 'selectGroupList', '✅查询-组列表', 'sql', NULL, '{\"table\": \"_group\", \"operation\": \"select\"}', '', '', 'update', 'vscode', 'vscode', '2022-07-04T22:27:58+08:00');
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (241, NULL, NULL, 'taskCreateManagement', 'selectWorkflowList', '✅获取流程列表', 'sql', NULL, '{\"table\": \"workflow\", \"operation\": \"select\"}', '', '', 'update', 'vscode', 'vscode', '2022-10-12T23:34:50+08:00');
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (242, NULL, '{}', 'taskCreateManagement', 'insertItem', '✅新增任务', 'service', NULL, '{\"service\":\"task\",\"serviceFunction\":\"createTask\"}', '', '', 'update', 'vscode', 'vscode', '2022-10-12T23:34:50+08:00');
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (251, NULL, '{\"before\":[{\"service\":\"task\",\"serviceFunction\":\"whereToViewUserId\"}]}', 'taskICreateManagement', 'selectItemList', '✅查询-查询列表', 'sql', '{}', '{\"table\": \"view01_task\", \"operation\": \"select\"}', '', '', 'update', 'vscode', 'vscode', '2022-07-02T22:48:31+08:00');
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (252, NULL, '', 'taskHistoryManagement', 'getTaskHistoryInfo', '✅获取任务历史详情', 'service', NULL, '{\"service\": \"task\", \"serviceFunction\": \"getTaskHistoryInfo\"}', '', '', 'update', 'vscode', 'vscode', '2022-07-04T22:22:35+08:00');
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (253, NULL, '', 'taskHistoryManagement', 'submitNode', '✅节点流转', 'service', NULL, '{\"service\": \"task\", \"serviceFunction\": \"submitNode\"}', '', '', 'update', 'vscode', 'vscode', '2022-07-04T22:22:35+08:00');
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (333, NULL, NULL, 'purchaseOrderDetail', 'getPurchaseOrderDetail', '✅获取采购订单详情', 'service', '{}', '{\"service\":\"purchase\",\"serviceFunction\":\"getPurchaseOrderDetail\"}', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (339, NULL, NULL, 'allPage', 'uploadFileDone', '✅ 文件分片上传-所有分片上传完毕', 'service', '{}', '{\"service\": \"file\", \"serviceFunction\": \"uploadFileDone\"}', '', '', 'update', NULL, NULL, '2022-05-04T16:02:58+08:00');
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (340, NULL, NULL, 'allPage', 'httpUploadByStream', '✅ 文件分片上传-http文件流', 'service', '{}', '{\"service\": \"file\", \"serviceFunction\": \"uploadFileChunkByStream\"}', '', '', 'update', NULL, NULL, '2022-05-04T16:02:58+08:00');
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (346, NULL, '{\"before\":[{\"service\":\"task\",\"serviceFunction\":\"historyFilterHook\"}]}', 'taskICreateManagement', 'selectTaskHistoryList', '✅查询列表', 'sql', '{}', '{ \"table\": \"task_history\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (348, NULL, '', 'purchaseOrderApply', 'selectItemList', '✅查询列表', 'sql', '{}', '{ \"table\": \"view01_purchase_order\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (349, NULL, NULL, 'purchaseOrderApply', 'selectGoodPriceStockList', '✅查询商品报价库存列表', 'sql', '{}', '{ \"table\": \"view02_good_price_stock\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (350, NULL, NULL, 'purchaseOrderApply', 'savePurchaseOrderDraft', '✅保存草稿', 'service', '{}', '{ \"service\": \"purchase\", \"serviceFunction\": \"savePurchaseOrderDraft\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (351, NULL, NULL, 'purchaseOrderApply', 'updatePurchaseOrderDraft', '✅更新', 'service', '{}', '{ \"service\": \"purchase\", \"serviceFunction\": \"updatePurchaseOrderDraft\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (352, NULL, '{\"after\":[{\"service\":\"purchase\",\"serviceFunction\":\"deletePurchaseOrderGoodList\"}]}', 'purchaseOrderApply', 'deleteItem', '✅删除', 'sql', '{}', '{ \"table\": \"purchase_order\", \"operation\": \"jhDelete\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (353, NULL, NULL, 'purchaseOrderApply', 'goodSelect-selectGoodPriceStockList', '✅查询商品报价库存列表', 'sql', '{}', '{ \"table\": \"view01_good_price_stock\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (354, NULL, NULL, 'purchaseOrderApply', 'submitPurchaseOrder', '✅提交', 'service', '{}', '{ \"service\": \"purchase\", \"serviceFunction\": \"submitPurchaseOrder\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (355, NULL, NULL, 'purchaseOrderApply', 'updatePurchaseOrderStatus', '✅更新采购单状态', 'service', '{}', '{ \"service\": \"purchase\", \"serviceFunction\": \"updatePurchaseOrderStatus\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (356, NULL, NULL, 'purchaseOrderApply', 'selectWorkflowList', '✅查询审核流程列表', 'sql', '{}', '{ \"table\": \"workflow\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (357, NULL, NULL, 'purchaseOrderApply', 'selectDeptList', '✅查询部门列表', 'sql', '{}', '{ \"table\": \"dept\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (361, NULL, '', 'purchaseOrderManagement', 'selectItemList', '✅查询列表', 'sql', '{}', '{ \"table\": \"view01_purchase_order\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (362, NULL, NULL, 'purchaseOrderManagement', 'goodSelect-selectGoodPriceStockList', '✅查询商品报价库存列表', 'sql', '{}', '{ \"table\": \"view01_good_price_stock\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (363, NULL, '{\"after\":[{\"service\":\"purchase\",\"serviceFunction\":\"appendPurchaseOrderGoodList\"}]}', 'purchaseOrderManagement', 'supplierSelect-getSupplierList', '✅supplierSelect-查询商品供应商列表', 'sql', '{}', '{ \"table\": \"view01_supplier_good\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (364, NULL, '', 'purchaseOrderManagement', 'supplierSelect-updateItem', '✅supplierSelect-更新成员', 'service', '{}', '{\"service\": \"purchase\", \"serviceFunction\": \"updatePurchaseOrderGoodSupplierAndPrice\"}', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (365, NULL, '', 'purchaseOrderManagement', 'createWorkflowTask', '✅生成工作流任务', 'service', '{}', '{\"service\":\"purchase\",\"serviceFunction\":\"createWorkflowTask\"}', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (366, NULL, NULL, 'purchaseOrderManagement', 'supplierSelect-selectGoodPriceStockList', '✅查询商品报价库存列表', 'sql', '{}', '{ \"table\": \"view01_good_price_stock\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (367, NULL, NULL, 'purchaseOrderManagement', 'selectSupplierGoodList', '✅查询供应商商品', 'sql', '{}', '{ \"table\": \"view01_supplier_good\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (368, NULL, NULL, 'purchaseOrderManagement', 'updatePurchaseOrderStatus', '✅更新采购单状态', 'service', '{}', '{ \"service\": \"purchase\", \"serviceFunction\": \"updatePurchaseOrderStatus\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (371, NULL, '{\"after\":[{\"service\":\"purchase\",\"serviceFunction\":\"appendPurchaseOrderGoodList\"}]}', 'purchaseOrderContract', 'selectItemList', '✅查询列表', 'sql', '{}', '{ \"table\": \"view01_purchase_order\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (373, NULL, NULL, 'purchaseOrderManagement', 'contractUpload-selectItemList', '✅purchaseOrderContractManagement查询-查询列表', 'sql', '{}', '{ \"table\": \"purchase_order_contract\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (374, NULL, '{\"before\":[{\"service\":\"purchaseContract\",\"serviceFunction\":\"fillInsertItemParamsBeforeHook\"}]}', 'purchaseOrderManagement', 'contractUpload-insertItem', '✅purchaseOrderContractManagement查询-添加成员', 'sql', '{}', '{ \"table\": \"purchase_order_contract\", \"operation\": \"insert\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (375, NULL, NULL, 'purchaseOrderManagement', 'contractUpload-updateItem', '✅purchaseOrderContractManagement查询-更新成员', 'sql', '{}', '{ \"table\": \"purchase_order_contract\", \"operation\": \"jhUpdate\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (376, NULL, NULL, 'purchaseOrderManagement', 'contractUpload-deleteItem', '✅purchaseOrderContractManagement查询-删除信息', 'sql', '{}', '{ \"table\": \"purchase_order_contract\", \"operation\": \"jhDelete\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (377, NULL, NULL, 'purchaseOrderApply', 'updatePurchaseOrderInfo', '✅更新采购单信息', 'service', '{}', '{ \"service\": \"purchase\", \"serviceFunction\": \"updatePurchaseOrderInfo\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (378, NULL, NULL, 'purchaseOrderManagement', 'selectPurchaseOrderGoodList', '✅查询采购单商品列表', 'sql', '{}', '{ \"table\": \"view02_purchase_order_good_store\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (379, NULL, NULL, 'purchaseOrderApply', 'getCurrentUserDept', '✅获取当前用户的部门', 'service', '{}', '{ \"service\": \"purchase\", \"serviceFunction\": \"getCurrentUserDept\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (380, NULL, NULL, 'purchaseOrderApply', 'selectUserList', '✅查询用户列表', 'sql', '{}', '{ \"table\": \"_view01_user\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (381, NULL, NULL, 'purchaseOrderApply', 'selectPurchaseOrderGoodList', '✅查询采购单商品列表', 'sql', '{}', '{ \"table\": \"view01_purchase_order_good\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
INSERT INTO `_resource` (`id`, `accessControlTable`, `resourceHook`, `pageId`, `actionId`, `desc`, `resourceType`, `appDataSchema`, `resourceData`, `requestDemo`, `responseDemo`, `operation`, `operationByUserId`, `operationByUser`, `operationAt`) VALUES (382, NULL, NULL, 'purchaseOrderManagement', 'selectGoodHistoryPriceList', '✅查询商品的历史报价', 'sql', '{}', '{ \"table\": \"view01_good_history_price\", \"operation\": \"select\" }', '', '', 'insert', NULL, NULL, NULL);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
